package de.hs.inform.lyuz.cookbook.gui;

import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import de.hs.inform.lyuz.cookbook.controller.manager.CategoryManager;
import de.hs.inform.lyuz.cookbook.utils.ConfUtils;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

public class CategoryPanel extends MyPanel {

    private DefaultListModel catTempListModel;
    private DefaultListModel catExtraListModel;

    private CategoryManager categoryManager;

    public CategoryPanel(CookMainJFrame cookConvert) {

        super(cookConvert);

        initComponents();
        init();

        categoryManager = new CategoryManager();
    }

    @Override
    protected void reload() {
        catTempListModel = new DefaultListModel();
        catExtraListModel = new DefaultListModel();

        this.myBook.getCatTemplate().forEach((ct) -> {
            catTempListModel.addElement(ct);
        });
        catTempList.setModel(catTempListModel);

        this.myBook.getCatExtra().forEach((s) -> {
            catExtraListModel.addElement(s);
        });
        catExtraList.setModel(catExtraListModel);
    }

    private void init() {

        //TODO: 点击空白处,取消所选选项
        catTempList.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JList list = (JList) e.getSource();

                if (list.locationToIndex(e.getPoint()) == -1 && !e.isShiftDown() && !isMenuShortcutKeyDown(e)) {
                    list.clearSelection();
                }
            }
        }
        );
    }

    private boolean isMenuShortcutKeyDown(InputEvent event) {
        return (event.getModifiers()
                & Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) != 0;

    }

    private void switchListModel(DefaultListModel dModel, int index, boolean UOD) {
        Object n1 = dModel.get(index);
        Object n2;
        if (UOD) {
            if (index != 0) {
                n2 = dModel.get(index - 1);
                dModel.set(index, n2);
                dModel.set(index - 1, n1);
            }
        } else {
            if (index != dModel.size() - 1) {
                n2 = dModel.get(index + 1);
                dModel.set(index, n2);
                dModel.set(index + 1, n1);
            }
        }
    }

    private void renameTempList(int index) {
        String catItem = (String) catTempListModel.get(catTempList.getSelectedIndex());
        String rename = javax.swing.JOptionPane.showInputDialog("Bitte geben einen Name");
        if (rename != null && !rename.trim().equals("")) {
            rename = rename.toUpperCase();
            if (!cookConvert.getMyBook().getCatExtra().contains(rename) && !cookConvert.getMyBook().getCatTemplate().contains(rename)) {
                catTempListModel.remove(index);
                catTempListModel.add(index, rename);

                categoryManager.renameCategory(cookConvert.getMyBook(), catItem, rename);
            } else {
                JOptionPane.showMessageDialog(null, "Der Name ist schon vorhanden", "Warnung", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catTemplateSP = new javax.swing.JScrollPane();
        catTempList = new javax.swing.JList<>();
        catTempLabel = new javax.swing.JLabel();
        catExtraLabel = new javax.swing.JLabel();
        catExtraSP = new javax.swing.JScrollPane();
        catExtraList = new javax.swing.JList<>();
        deleteBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        toExpBtn = new javax.swing.JButton();
        leftBtn = new javax.swing.JButton();
        renameBtn = new javax.swing.JButton();
        allocateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        saveCatBtn = new javax.swing.JButton();

        catTempList.setToolTipText("die kategorien zum Export zeigen");
        catTempList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTempListMouseClicked(evt);
            }
        });
        catTemplateSP.setViewportView(catTempList);

        catTempLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        catTempLabel.setText("vorhandene Kategorien");

        catExtraLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        catExtraLabel.setText("extra kategoorien");

        catExtraList.setToolTipText("extra kategorien von importierten Dateien zeigen");
        catExtraSP.setViewportView(catExtraList);

        deleteBtn.setText("löschen");
        deleteBtn.setToolTipText("Bitte eine Kategorie aus linken Seite auswählen");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        upBtn.setText("nach oben");
        upBtn.setToolTipText("Bitte eine Kategorie aus linken Seite auswählen");
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.setText("nach unter");
        downBtn.setToolTipText("Bitte eine Kategorie aus linken Seite auswählen");
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        toExpBtn.setText("nächst");
        toExpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toExpBtnActionPerformed(evt);
            }
        });

        leftBtn.setText("nach rechts");
        leftBtn.setToolTipText("Bitte eine Kategorie aus rechte Seite auswählen");
        leftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBtnActionPerformed(evt);
            }
        });

        renameBtn.setText("umbenennen");
        renameBtn.setToolTipText("Umbenennen nur für vorhandene Kategorien");
        renameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameBtnActionPerformed(evt);
            }
        });

        allocateBtn.setText("zuordnen");
        allocateBtn.setToolTipText("Bitte eine Kategorie auf jede Spalte auswählen");
        allocateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("zurück");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveCatBtn.setText("speichern");
        saveCatBtn.setToolTipText("vorhandene Kategorien als Muster speichern");
        saveCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toExpBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(catTempLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(catExtraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(catTemplateSP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftBtn)
                            .addComponent(upBtn)
                            .addComponent(downBtn)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(renameBtn)
                            .addComponent(allocateBtn)
                            .addComponent(saveCatBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(catExtraSP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {allocateBtn, deleteBtn, downBtn, leftBtn, renameBtn, saveCatBtn, upBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(catTempLabel)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(downBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(renameBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allocateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveCatBtn))
                            .addComponent(catTemplateSP, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(catExtraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catExtraSP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toExpBtn)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {allocateBtn, deleteBtn, downBtn, leftBtn, renameBtn, saveCatBtn, upBtn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backBtn, toExpBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        if (catTempList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie eine Kategorie aus linken Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int index = catTempList.getSelectedIndex();
        switchListModel(catTempListModel, index, false);

        if (index != catTempListModel.size() - 1) {
            catTempList.setSelectedIndex(index + 1);
        }
    }//GEN-LAST:event_downBtnActionPerformed

    private void toExpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toExpBtnActionPerformed
        if (myBook.getFiles().isEmpty()) {
            Object[] options = {"zurück", "nächst"};
            int n = JOptionPane.showOptionDialog(null, "Keine Datein werden importiert.\n Wollen Sie weiter machen?", "Warnung", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (n == 0) {
                return;
            }
        } else if (myBook.getCatTemplate().size() == 0) {
            Object[] options = {"zurück", "nächst"};
            int n = JOptionPane.showOptionDialog(null, "Keine Kategorien sind vorhanden.\n Wollen Sie weiter machen?", "Warnung", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (n == 0) {
                return;
            }
        }
        cookConvert.getCookTabPane().setSelectedComponent(cookConvert.getExportPanel());
    }//GEN-LAST:event_toExpBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed

        if (catTempList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie eine Kategorie aus linken Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int index = catTempList.getSelectedIndex();
        switchListModel(catTempListModel, index, true);

        if (index != 0) {
            catTempList.setSelectedIndex(index - 1);
        }
    }//GEN-LAST:event_upBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        if (!catTempList.isSelectionEmpty()) {
            JCheckBox checkbox = new JCheckBox("Löschen alle Rezepte unter dieser Kategorie,");
            String tipp = "\t \t \t sonst werden die Rezepte zu ANDERE zugeordnet.";
            String message = "Wollen Sie die Kategorie" + catTempListModel.get(catTempList.getSelectedIndex()) + " löschen?\n";
            Object[] params = {message, "\n", checkbox, tipp};
            int n = JOptionPane.showConfirmDialog(null, params, "Löschen", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                String catItem = (String) catTempListModel.get(catTempList.getSelectedIndex());
                catTempListModel.remove(catTempList.getSelectedIndex());
                categoryManager.removeCategory(cookConvert.getMyBook(), catItem, checkbox.isSelected());

                if (!checkbox.isSelected()) {
                    int i = 0;
                    for (i = 0; i < catTempListModel.getSize(); i++) {
                        String catS = (String) catTempListModel.get(i);
                        if (catS.equals("ANDERE")) {
                            break;
                        }
                    }
                    if (i == catTempListModel.getSize()) {
                        catTempListModel.addElement("ANDERE");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie eine Kategorie aus linken Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void leftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBtnActionPerformed
        if (!catExtraList.isSelectionEmpty()) {
            int n = JOptionPane.showConfirmDialog(null, "Wollen Sie die Kategorie " + catExtraListModel.get(catExtraList.getSelectedIndex())
                    + " auf der linken Seite hinzufügen, \n damit werden alle Rezepte unter der Kategorie importiert", "Warnung", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                String catItem = (String) catExtraListModel.get(catExtraList.getSelectedIndex());

                catTempListModel.addElement(catItem);
                catExtraListModel.remove(catExtraList.getSelectedIndex());

                categoryManager.leftCategory(cookConvert.getMyBook(), catItem);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie eine Kategorie aus rechten Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_leftBtnActionPerformed

    private void renameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameBtnActionPerformed
        if (catTempList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie eine Kategorie aus linken Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else {
            int index = catTempList.getSelectedIndex();
            renameTempList(index);
        }
    }//GEN-LAST:event_renameBtnActionPerformed

    private void allocateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateBtnActionPerformed
        if (catExtraList.isSelectionEmpty() && catTempList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie jeweils eine Kategrie aus ", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (catExtraList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie noch eine Kategorie aus rechten Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (catTempList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie noch eine Kategorie aus linken Seite aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else {
            int n = JOptionPane.showConfirmDialog(null, "Wollen Sie die Kategorie" + catExtraListModel.get(catExtraList.getSelectedIndex())
                    + " zu " + catTempListModel.get(catTempList.getSelectedIndex()) + " zuordenen ?",
                    "Frage", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                String cat1 = (String) catExtraListModel.get(catExtraList.getSelectedIndex());
                String cat2 = (String) catTempListModel.get(catTempList.getSelectedIndex());
                catExtraListModel.remove(catExtraList.getSelectedIndex());

                categoryManager.allocateCatList(cookConvert.getMyBook(), cat1, cat2);
            }
        }
    }//GEN-LAST:event_allocateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cookConvert.getCookTabPane().setSelectedComponent(cookConvert.getImportPanel());
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCatBtnActionPerformed
        if (myBook.getCatTemplate().size() == 0) {
            JOptionPane.showMessageDialog(null, "Keine Kategorien in linken Seite für Speichern", "Warnung", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int n = JOptionPane.showConfirmDialog(null, "Wollen Sie die vorhanden Kategorien als Muster speichern?", "Warnung", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            try {
                ConfUtils.updateCatTemplate(myBook.getCatTemplate());
            } catch (IOException ex) {
                Logger.getLogger(CategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Fehler beim Spreichern Kategorien", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveCatBtnActionPerformed

    private void catTempListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTempListMouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            if (index > -1) {
                renameTempList(index);
            }
        }
    }//GEN-LAST:event_catTempListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allocateBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel catExtraLabel;
    private javax.swing.JList<String> catExtraList;
    private javax.swing.JScrollPane catExtraSP;
    private javax.swing.JLabel catTempLabel;
    private javax.swing.JList<String> catTempList;
    private javax.swing.JScrollPane catTemplateSP;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton downBtn;
    private javax.swing.JButton leftBtn;
    private javax.swing.JButton renameBtn;
    private javax.swing.JButton saveCatBtn;
    private javax.swing.JButton toExpBtn;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables

}
