package de.hs.inform.lyuz.cookbook.gui;

import de.hs.inform.lyuz.cookbook.logic.manager.ExportManager;
import javax.swing.JFileChooser;
import de.hs.inform.lyuz.cookbook.model.ExportInfo;
import de.hs.inform.lyuz.cookbook.model.MyBook;
import de.hs.inform.lyuz.cookbook.model.exception.ConvertErrorException;
import de.hs.inform.lyuz.cookbook.model.exception.SystemErrorException;
import de.hs.inform.lyuz.cookbook.utils.ConfUtils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

public class ExportPanel extends MyPanel {

    private String type = "";
    private String suffix = "";

    public ExportPanel(CookMainJFrame cookConvert) {

        super(cookConvert);

        initComponents();
        init();
    }

    @Override
    protected void reload() {
        bookNameTF.setText(myBook.getExportInfo().getBookname());
        pathTF.setText(myBook.getExportInfo().getFilepath());
    }

    private void init() {
        radioBtnG.add(epub2RBtn);
        radioBtnG.add(epub3RBtn);
        radioBtnG.add(cmlRBtn);
        radioBtnG.add(texRBtn);

        reload();
    }

    private boolean exportFile() {
        ExportInfo exportInfo = myBook.getExportInfo();
        exportInfo.updateExportInfo(bookNameTF.getText(), pathTF.getText() + File.separator, type);
        myBook.setExportInfo(exportInfo);

        try {
            ConfUtils.updateExportInfo(this.myBook.getExportInfo());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Fehler beim Speichern ExportInfor", "Fehler", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        MyBook mybook = this.myBook.myclone();

        ExportManager exportManager = new ExportManager(mybook);
        try {
            if (cmlRBtn.isSelected()) {
                exportManager.cmlExport();
            } else if (epub2RBtn.isSelected()) {
                exportManager.epub2Export();
            } else if (epub3RBtn.isSelected()) {
                exportManager.epub3Export();
            } else if (texRBtn.isSelected()) {
                exportManager.texExport();
            }
            mybook.setErrorMessage(mybook.getErrorMessage() + exportManager.getErrorMessage());
            ConfUtils.writeLog(mybook, null);
        } catch (ConvertErrorException | SystemErrorException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Fehler", JOptionPane.ERROR_MESSAGE);
            
            mybook.setErrorMessage(mybook.getErrorMessage() + exportManager.getErrorMessage());
            ConfUtils.writeLog(mybook, ex);
            return false;
        }

        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnG = new javax.swing.ButtonGroup();
        exportPanel = new javax.swing.JPanel();
        exportRadioPanel = new javax.swing.JPanel();
        epub2RBtn = new javax.swing.JRadioButton();
        epub3RBtn = new javax.swing.JRadioButton();
        cmlRBtn = new javax.swing.JRadioButton();
        texRBtn = new javax.swing.JRadioButton();
        setBtn = new javax.swing.JButton();
        exportTippSP = new javax.swing.JScrollPane();
        exportTippTA = new javax.swing.JTextArea();
        exportBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        bookNameLabel = new javax.swing.JLabel();
        bookNameTF = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathTF = new javax.swing.JTextField();
        bookPathBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 370));

        exportRadioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Export Format"));

        epub2RBtn.setText("EPUB2");
        epub2RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epub2RBtnActionPerformed(evt);
            }
        });

        epub3RBtn.setText("EPUB3");
        epub3RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epub3RBtnActionPerformed(evt);
            }
        });

        cmlRBtn.setText("CML");
        cmlRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmlRBtnActionPerformed(evt);
            }
        });

        texRBtn.setText("LATEX");
        texRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRBtnActionPerformed(evt);
            }
        });

        setBtn.setText("...");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exportRadioPanelLayout = new javax.swing.GroupLayout(exportRadioPanel);
        exportRadioPanel.setLayout(exportRadioPanelLayout);
        exportRadioPanelLayout.setHorizontalGroup(
            exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportRadioPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(epub2RBtn)
                    .addComponent(epub3RBtn)
                    .addComponent(texRBtn)
                    .addComponent(cmlRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        exportRadioPanelLayout.setVerticalGroup(
            exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportRadioPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epub2RBtn)
                    .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epub3RBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmlRBtn))
        );

        exportTippTA.setEditable(false);
        exportTippTA.setBackground(new java.awt.Color(238, 238, 238));
        exportTippTA.setColumns(2);
        exportTippTA.setRows(2);
        exportTippTA.setText("Tipp: Bitte wählen Sie ein Ausgabe-Format aus.");
        exportTippSP.setViewportView(exportTippTA);

        exportBtn.setText("exportieren");
        exportBtn.setToolTipText("");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        backBtn.setText("zurück");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        bookNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bookNameLabel.setText("Datei Name");

        bookNameTF.setText("CookBook");

        pathLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pathLabel.setText("Speichern als");

        bookPathBtn.setText("...");
        bookPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exportPanelLayout = new javax.swing.GroupLayout(exportPanel);
        exportPanel.setLayout(exportPanelLayout);
        exportPanelLayout.setHorizontalGroup(
            exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addComponent(exportTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportBtn)
                        .addGap(123, 123, 123))
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(exportPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(exportPanelLayout.createSequentialGroup()
                                        .addComponent(pathLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(exportPanelLayout.createSequentialGroup()
                                        .addComponent(bookNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(bookNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(exportRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(113, Short.MAX_VALUE))))
        );

        exportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backBtn, exportBtn});

        exportPanelLayout.setVerticalGroup(
            exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportBtn)
                    .addComponent(backBtn))
                .addGap(14, 14, 14))
        );

        exportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backBtn, exportBtn});

        exportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bookNameLabel, pathLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void epub2RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epub2RBtnActionPerformed
        exportTippTA.setText("EPUB2 exportieren ....");
        type = "EPUB2";
        suffix = ".epub";
    }//GEN-LAST:event_epub2RBtnActionPerformed

    private void epub3RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epub3RBtnActionPerformed
        exportTippTA.setText("EPUB3 exportieren....");
        type = "EPUB3";
        suffix = ".epub";
    }//GEN-LAST:event_epub3RBtnActionPerformed

    private void cmlRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmlRBtnActionPerformed
        exportTippTA.setText("CML exportieren ....");
        type = "CML";
        suffix = ".cml";
    }//GEN-LAST:event_cmlRBtnActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        String path = pathTF.getText();
        if (!pathTF.getText().equals("")) {
            path += File.separator;
        }

        File f = new File(path);
        if (!f.exists()) {
            JOptionPane.showMessageDialog(null, "Bitte geben Sie einen gültigen Pfad ein", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (type.equals("")) {
            JOptionPane.showMessageDialog(null, "Bitte wählen Sie ein Export-Format aus", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (myBook.getFiles().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte importieren Sie eine Datei", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (myBook.getCatTemplate().size() == 0) {
            JOptionPane.showMessageDialog(null, "Keine Kategorien sind vorhanden", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else {
            f = new File(path + bookNameTF.getText() + suffix);
            int n;
            if (f.exists()) {
                n = JOptionPane.showConfirmDialog(null, "Wollen Sie die " + bookNameTF.getText() + suffix + " ersetzen?", "Frage", JOptionPane.YES_NO_OPTION);
            } else {
                n = JOptionPane.showConfirmDialog(null, "Wollen Sie ein " + type.toUpperCase() + " Kochbuch exportieren?", "Frage", JOptionPane.YES_NO_OPTION);
            }
            if (n == 0) {
                if (exportFile()) {
                    JOptionPane.showMessageDialog(null, "Kochbuch ist erfolgreich erstellt", "Erfolg", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_exportBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cookConvert.getCookTabPane().setSelectedComponent(cookConvert.getCategoryPanel());
    }//GEN-LAST:event_backBtnActionPerformed

    private void texRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRBtnActionPerformed
        exportTippTA.setText("Latex exportieren....");
        type = "LATEX";
        suffix = ".tex";
    }//GEN-LAST:event_texRBtnActionPerformed

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        SettingDialog dialog = new SettingDialog(cookConvert, true);
        dialog.setVisible(true);

        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                myBook.setExportInfo(dialog.getExportInfo());
            }
        });
    }//GEN-LAST:event_setBtnActionPerformed

    private void bookPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPathBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY | JFileChooser.SAVE_DIALOG);
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        int result = fc.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            pathTF.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bookPathBtnActionPerformed

    public String getType() {
        return type;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTF;
    private javax.swing.JButton bookPathBtn;
    private javax.swing.JRadioButton cmlRBtn;
    private javax.swing.JRadioButton epub2RBtn;
    private javax.swing.JRadioButton epub3RBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JPanel exportPanel;
    private javax.swing.JPanel exportRadioPanel;
    private javax.swing.JScrollPane exportTippSP;
    private javax.swing.JTextArea exportTippTA;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTF;
    private javax.swing.ButtonGroup radioBtnG;
    private javax.swing.JButton setBtn;
    private javax.swing.JRadioButton texRBtn;
    // End of variables declaration//GEN-END:variables
}
