package de.hs.inform.lyuz.cookbook.gui;

import de.hs.inform.lyuz.cookbook.controller.manager.ExportManager;
import javax.swing.JFileChooser;
import de.hs.inform.lyuz.cookbook.help.ExportInfo;

public class ExportPanel extends javax.swing.JPanel {

    private final CookMainJFrame cookConvert;

    public ExportPanel(CookMainJFrame cookConvert) {

        this.cookConvert = cookConvert;

        initComponents();
        init();
    }

    private void init() {
        radioBtnG.add(epub2RBtn);
        radioBtnG.add(epub3RBtn);
        radioBtnG.add(cmlRBtn);
        radioBtnG.add(texRBtn);
        
        bookNameTF.setText(ExportInfo.bookname);
        pathTF.setText(ExportInfo.filepath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnG = new javax.swing.ButtonGroup();
        exportPanel = new javax.swing.JPanel();
        exportRadioPanel = new javax.swing.JPanel();
        epub2RBtn = new javax.swing.JRadioButton();
        epub3RBtn = new javax.swing.JRadioButton();
        cmlRBtn = new javax.swing.JRadioButton();
        texRBtn = new javax.swing.JRadioButton();
        setBtn = new javax.swing.JButton();
        exportTippSP = new javax.swing.JScrollPane();
        exportTippTA = new javax.swing.JTextArea();
        exportBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        bookNameLabel = new javax.swing.JLabel();
        bookNameTF = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathTF = new javax.swing.JTextField();
        bookPathBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 370));

        exportRadioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Export Format"));

        epub2RBtn.setText("EPUB2");
        epub2RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epub2RBtnActionPerformed(evt);
            }
        });

        epub3RBtn.setText("EPUB3");
        epub3RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epub3RBtnActionPerformed(evt);
            }
        });

        cmlRBtn.setText("CML");
        cmlRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmlRBtnActionPerformed(evt);
            }
        });

        texRBtn.setText("LATEX");
        texRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRBtnActionPerformed(evt);
            }
        });

        setBtn.setText("...");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exportRadioPanelLayout = new javax.swing.GroupLayout(exportRadioPanel);
        exportRadioPanel.setLayout(exportRadioPanelLayout);
        exportRadioPanelLayout.setHorizontalGroup(
            exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportRadioPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(epub2RBtn)
                    .addComponent(epub3RBtn)
                    .addComponent(texRBtn)
                    .addComponent(cmlRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        exportRadioPanelLayout.setVerticalGroup(
            exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportRadioPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(exportRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epub2RBtn)
                    .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epub3RBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmlRBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exportTippTA.setEditable(false);
        exportTippTA.setBackground(new java.awt.Color(238, 238, 238));
        exportTippTA.setColumns(2);
        exportTippTA.setRows(2);
        exportTippTA.setText("Tip: select an export format.");
        exportTippSP.setViewportView(exportTippTA);

        exportBtn.setText("SAVE");
        exportBtn.setToolTipText("");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        bookNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bookNameLabel.setText("file name:");

        bookNameTF.setText("CookBook");

        pathLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pathLabel.setText("save as:");

        bookPathBtn.setText("...");
        bookPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exportPanelLayout = new javax.swing.GroupLayout(exportPanel);
        exportPanel.setLayout(exportPanelLayout);
        exportPanelLayout.setHorizontalGroup(
            exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportPanelLayout.createSequentialGroup()
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportBtn)
                        .addGap(10, 10, 10))
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exportPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pathLabel)
                                    .addComponent(bookNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookNameTF)
                                    .addGroup(exportPanelLayout.createSequentialGroup()
                                        .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(exportPanelLayout.createSequentialGroup()
                                .addContainerGap(10, Short.MAX_VALUE)
                                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exportTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exportRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)))
                .addGap(41, 41, 41))
        );

        exportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backBtn, exportBtn});

        exportPanelLayout.setVerticalGroup(
            exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel))
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pathLabel)
                        .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exportPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bookPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(exportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(exportBtn))
                .addGap(14, 14, 14))
        );

        exportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backBtn, exportBtn});

        exportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bookNameLabel, bookNameTF, pathLabel, pathTF});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(exportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void epub2RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epub2RBtnActionPerformed
        exportTippTA.setText("Export EPUB2 ....");
        ExportInfo.exportTyp = "EPUB2";
    }//GEN-LAST:event_epub2RBtnActionPerformed

    private void epub3RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epub3RBtnActionPerformed
        exportTippTA.setText("Export EPUB3 ....");
        ExportInfo.exportTyp = "EPUB3";
    }//GEN-LAST:event_epub3RBtnActionPerformed

    private void cmlRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmlRBtnActionPerformed
        exportTippTA.setText("Export CML ....");
        ExportInfo.exportTyp = "CML";
    }//GEN-LAST:event_cmlRBtnActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        String path = pathTF.getText();
        if(!pathTF.getText().equals("")) {
            path += "/";
        }
        ExportInfo.updateExportInfo(bookNameTF.getText(), path);

        ExportManager exportManager = new ExportManager(cookConvert.getMyBook());
                     
        if (cmlRBtn.isSelected()) {
            exportManager.cmlExport();       
        } else if (epub2RBtn.isSelected()) {
            exportManager.epub2Export();
        } else if (epub3RBtn.isSelected()) {
            exportManager.epub3Export();
        } else if (texRBtn.isSelected()) {
            exportManager.texExport();           
        }
    }//GEN-LAST:event_exportBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cookConvert.getCookTabPane().setSelectedComponent(CookMainJFrame.categoryPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void texRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRBtnActionPerformed
        exportTippTA.setText("Export Latex ....");
        ExportInfo.exportTyp = "LATEX";
    }//GEN-LAST:event_texRBtnActionPerformed

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        SettingDialog dialog = new SettingDialog(cookConvert, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_setBtnActionPerformed

    private void bookPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPathBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY | JFileChooser.SAVE_DIALOG);
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        fc.showSaveDialog(null);
        pathTF.setText(fc.getSelectedFile().getPath());
    }//GEN-LAST:event_bookPathBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTF;
    private javax.swing.JButton bookPathBtn;
    private javax.swing.JRadioButton cmlRBtn;
    private javax.swing.JRadioButton epub2RBtn;
    private javax.swing.JRadioButton epub3RBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JPanel exportPanel;
    private javax.swing.JPanel exportRadioPanel;
    private javax.swing.JScrollPane exportTippSP;
    private javax.swing.JTextArea exportTippTA;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTF;
    private javax.swing.ButtonGroup radioBtnG;
    private javax.swing.JButton setBtn;
    private javax.swing.JRadioButton texRBtn;
    // End of variables declaration//GEN-END:variables
}
