package de.hs.inform.lyuz.cookbook.gui;

import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class ImportPanel extends javax.swing.JPanel {

    private ArrayList<File> files;
    private DefaultListModel list;

    private final CookMainJFrame cookConvert;

    public static boolean action = false;

    /**
     * Creates new form ImportPanel
     *
     * @param cookConvert
     */
    public ImportPanel(CookMainJFrame cookConvert) {
        this.cookConvert = cookConvert;

        initComponents();
        init();
        
    }
    
    private void init() {
        
        this.files = new ArrayList<>();
        
        this.list = new DefaultListModel();
        fileList.setModel(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importPanel = new javax.swing.JPanel();
        fileListSP = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList<>();
        openBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        openTippSP = new javax.swing.JScrollPane();
        tippTA = new javax.swing.JTextArea();
        toCatBtn = new javax.swing.JButton();
        fileDeleteBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 370));

        fileListSP.setViewportView(fileList);

        openBtn.setText("ADD");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("List of  Imoport Files");

        tippTA.setEditable(false);
        tippTA.setBackground(new java.awt.Color(238, 238, 238));
        tippTA.setColumns(2);
        tippTA.setLineWrap(true);
        tippTA.setRows(2);
        tippTA.setText("Tip: You can open many files and export them into a file.");
        openTippSP.setViewportView(tippTA);

        toCatBtn.setText("NEXT");
        toCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCatBtnActionPerformed(evt);
            }
        });

        fileDeleteBtn.setText("DELETE");
        fileDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout importPanelLayout = new javax.swing.GroupLayout(importPanel);
        importPanel.setLayout(importPanelLayout);
        importPanelLayout.setHorizontalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toCatBtn)
                .addGap(56, 56, 56))
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addComponent(fileListSP, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openBtn)
                            .addComponent(fileDeleteBtn)))
                    .addComponent(jLabel3))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        importPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fileDeleteBtn, openBtn});

        importPanelLayout.setVerticalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileDeleteBtn))
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileListSP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(openTippSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toCatBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(importPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(importPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed

        JFileChooser fc = new JFileChooser() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith("mcb") || f.isDirectory()
                        || f.getName().endsWith("cml")
                        || f.getName().endsWith("mm")
                        || f.getName().endsWith("bs");
            }
        };
        fc.setMultiSelectionEnabled(true);
        int result = fc.showOpenDialog(this);

        switch (result) {
            case JFileChooser.APPROVE_OPTION:
                File file = file = fc.getSelectedFile();
                for (int i = 0; i < files.size(); i++) {
                    if (files.get(i).getAbsolutePath().equals(file.getAbsolutePath())) {
                        JOptionPane.showMessageDialog(null, "Es gibt schon das File", "Warnung", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                files.add(file);
                list.addElement(file.getName() + "  " + file.getPath());
                action = true;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_openBtnActionPerformed

    private void toCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCatBtnActionPerformed
        if (files.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte, geben Sie ein File", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else {
            cookConvert.getCookTabPane().setSelectedComponent(CookMainJFrame.categoryPanel);
        }
    }//GEN-LAST:event_toCatBtnActionPerformed


    private void fileDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileDeleteBtnActionPerformed
        if (fileList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte ein File auswählen", "Warnung", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ArrayList<String> deleteList = (ArrayList<String>) fileList.getSelectedValuesList();

        for (String dlString : deleteList) {
            list.removeElement((Object) dlString);
            String[] split = dlString.split(" ");
            String name = split[0];
            String path = split[2];
            for (File f : files) {
                if (f.getPath().equals(path) && f.getName().equals(name)) {
                    files.remove(f);
                    action = true;
                    break;
                }
            }
        }
    }//GEN-LAST:event_fileDeleteBtnActionPerformed

    public ArrayList<File> getFiles() {
        return files;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileDeleteBtn;
    private javax.swing.JList<String> fileList;
    private javax.swing.JScrollPane fileListSP;
    private javax.swing.JPanel importPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton openBtn;
    private javax.swing.JScrollPane openTippSP;
    private javax.swing.JTextArea tippTA;
    private javax.swing.JButton toCatBtn;
    // End of variables declaration//GEN-END:variables
}
