package de.hs.inform.lyuz.cookbook.gui;

import java.io.File;
import javax.swing.JFileChooser;
import de.hs.inform.lyuz.cookbook.model.ExportInfo;
import de.hs.inform.lyuz.cookbook.utils.ConfUtils;
import java.io.IOException;
import javax.swing.JOptionPane;

public class SettingDialog extends javax.swing.JDialog {

    private ExportInfo exportInfo;

    public SettingDialog(CookMainJFrame parent, boolean modal) {
        super(parent, modal);

        exportInfo = parent.getMyBook().getExportInfo();

        initComponents();
        init(parent.getExportPanel().getType());

        setLocationRelativeTo(null);
    }

    private void init(String type) {
        firstNameTF.setText(exportInfo.getFirstName());
        lastNameTF.setText(exportInfo.getLastName());
        titleTF.setText(exportInfo.getTitle());

        hasPicCB.setSelected(exportInfo.isHasPic());
        isColorCB.setSelected(exportInfo.isIsColor());

        hasCatCB.setSelected(exportInfo.isHasCat());
        hasIndexCB.setSelected(exportInfo.isHasIndex());
        hasSourceCB.setSelected(exportInfo.isHasSource());
        hasRemarkCB.setSelected(exportInfo.isHasRemark());
        hasTimeCB.setSelected(exportInfo.isHasTime());
        hasDifficultyCB.setSelected(exportInfo.isHasDiffculty());

        hasCover.setSelected(exportInfo.isHasCover());
        coverTF.setText(exportInfo.getCoverPath());
        coverTF.setEnabled(false);
        fileChooseBtn.setEnabled(false);

        switch (type) {
            case "LATEX":
                hasCatCB.setSelected(true);
                hasCatCB.setEnabled(false);
                hasCover.setEnabled(false);
                coverTF.setEnabled(false);
                fileChooseBtn.setEnabled(false);
                hasDifficultyCB.setEnabled(false);
                break;
            case "CML":
                hasIndexCB.setEnabled(false);
                isColorCB.setEnabled(false);
                hasCatCB.setEnabled(false);
                hasCover.setEnabled(false);
                coverTF.setEnabled(false);
                fileChooseBtn.setEnabled(false);
                break;
            case "EPUB3":
                hasCatCB.setSelected(true);
                hasCatCB.setEnabled(false);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        titleTF = new javax.swing.JTextField();
        hasPicPanel = new javax.swing.JPanel();
        hasPicCB = new javax.swing.JCheckBox();
        isColorCB = new javax.swing.JCheckBox();
        contentPanel = new javax.swing.JPanel();
        hasSourceCB = new javax.swing.JCheckBox();
        hasRemarkCB = new javax.swing.JCheckBox();
        hasCatCB = new javax.swing.JCheckBox();
        hasIndexCB = new javax.swing.JCheckBox();
        hasTimeCB = new javax.swing.JCheckBox();
        hasDifficultyCB = new javax.swing.JCheckBox();
        coverPanel = new javax.swing.JPanel();
        hasCover = new javax.swing.JCheckBox();
        coverTF = new javax.swing.JTextField();
        fileChooseBtn = new javax.swing.JButton();
        autorPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        titleLabel.setText("TITLEL");

        settingLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingLabel.setText("Einstellung");

        saveBtn.setText("speichern");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("abbrechnen");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        titleTF.setText("CookBook");

        hasPicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bilder"));

        hasPicCB.setSelected(true);
        hasPicCB.setText("Bilder");
        hasPicCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasPicCBActionPerformed(evt);
            }
        });

        isColorCB.setSelected(true);
        isColorCB.setText("Color");

        javax.swing.GroupLayout hasPicPanelLayout = new javax.swing.GroupLayout(hasPicPanel);
        hasPicPanel.setLayout(hasPicPanelLayout);
        hasPicPanelLayout.setHorizontalGroup(
            hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasPicPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(hasPicCB)
                .addGap(18, 18, 18)
                .addComponent(isColorCB)
                .addGap(46, 46, 46))
        );
        hasPicPanelLayout.setVerticalGroup(
            hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasPicPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasPicCB)
                    .addComponent(isColorCB)))
        );

        contentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Inhalt"));

        hasSourceCB.setText("Quelle");

        hasRemarkCB.setText("Bemerkung");

        hasCatCB.setSelected(true);
        hasCatCB.setText("Inhaltsverzeichnis");
        hasCatCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCatCBActionPerformed(evt);
            }
        });

        hasIndexCB.setText("Index");

        hasTimeCB.setSelected(true);
        hasTimeCB.setText("Kochenzeit");
        hasTimeCB.setToolTipText("");

        hasDifficultyCB.setSelected(true);
        hasDifficultyCB.setText("Schwerigkeit");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasCatCB)
                    .addComponent(hasDifficultyCB)
                    .addComponent(hasTimeCB))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasIndexCB)
                    .addComponent(hasSourceCB)
                    .addComponent(hasRemarkCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasCatCB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hasIndexCB))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasTimeCB)
                    .addComponent(hasSourceCB))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasDifficultyCB)
                    .addComponent(hasRemarkCB))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        coverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cover"));

        hasCover.setText("Cover");
        hasCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCoverActionPerformed(evt);
            }
        });

        fileChooseBtn.setText("...");
        fileChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coverPanelLayout = new javax.swing.GroupLayout(coverPanel);
        coverPanel.setLayout(coverPanelLayout);
        coverPanelLayout.setHorizontalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(hasCover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverTF, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        coverPanelLayout.setVerticalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(coverTF, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addComponent(hasCover))
            .addGroup(coverPanelLayout.createSequentialGroup()
                .addComponent(fileChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        autorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        firstNameLabel.setText("Vorname:");

        lastNameLabel.setText("Nachname:");

        firstNameTF.setText("Cooker");

        lastNameTF.setText("Cooker");

        javax.swing.GroupLayout autorPanelLayout = new javax.swing.GroupLayout(autorPanel);
        autorPanel.setLayout(autorPanelLayout);
        autorPanelLayout.setHorizontalGroup(
            autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autorPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(firstNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addGroup(autorPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNameTF)))
                .addContainerGap())
        );

        autorPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstNameTF, lastNameTF});

        autorPanelLayout.setVerticalGroup(
            autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(titleLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addComponent(hasPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(autorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(settingLabel)
                                .addComponent(coverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingLabel)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasCatCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCatCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasCatCBActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        if (titleTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bitte geben Sie einen Titel ein", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else if (firstNameTF.getText().equals("") || lastNameTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bitte geben Sie einen Name ein", "Warnung", JOptionPane.WARNING_MESSAGE);
        } else {
            exportInfo.updateBookInfo(firstNameTF.getText(), lastNameTF.getText(),
                    titleTF.getText(), hasPicCB.isSelected(), isColorCB.isSelected(),
                    hasCatCB.isSelected(), hasIndexCB.isSelected(),
                    hasSourceCB.isSelected(), hasRemarkCB.isSelected(),
                    hasTimeCB.isSelected(), hasDifficultyCB.isSelected(),
                    hasCover.isSelected(), coverTF.getText());
            try {
                ConfUtils.updateExportInfo(exportInfo);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Fehler beim Speichern Export Information", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void fileChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseBtnActionPerformed
        JFileChooser fc = new JFileChooser() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith("jpg") || f.isDirectory()
                        || f.getName().endsWith("png")
                        || f.getName().endsWith("jpeg")
                        || f.getName().endsWith("gif");
            }
        };
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        int result = fc.showOpenDialog(this);
        switch (result) {
            case JFileChooser.APPROVE_OPTION:
                File file = file = fc.getSelectedFile();
                coverTF.setText(file.getAbsolutePath());
                exportInfo.setCoverPath(file.getAbsolutePath());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_fileChooseBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void hasCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCoverActionPerformed
        if (!hasCover.isSelected()) {
            coverTF.setEnabled(false);
            fileChooseBtn.setEnabled(false);
        } else {
            coverTF.setEnabled(true);
            fileChooseBtn.setEnabled(true);
        }
    }//GEN-LAST:event_hasCoverActionPerformed

    private void hasPicCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasPicCBActionPerformed
        if (!hasPicCB.isSelected()) {
            isColorCB.setEnabled(false);
        } else {
            isColorCB.setEnabled(true);
        }
    }//GEN-LAST:event_hasPicCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autorPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel coverPanel;
    private javax.swing.JTextField coverTF;
    private javax.swing.JButton fileChooseBtn;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JCheckBox hasCatCB;
    private javax.swing.JCheckBox hasCover;
    private javax.swing.JCheckBox hasDifficultyCB;
    private javax.swing.JCheckBox hasIndexCB;
    private javax.swing.JCheckBox hasPicCB;
    private javax.swing.JPanel hasPicPanel;
    private javax.swing.JCheckBox hasRemarkCB;
    private javax.swing.JCheckBox hasSourceCB;
    private javax.swing.JCheckBox hasTimeCB;
    private javax.swing.JCheckBox isColorCB;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables

    public ExportInfo getExportInfo() {
        return exportInfo;
    }

}
