package de.hs.inform.lyuz.cookbook.gui;

import java.io.File;
import javax.swing.JFileChooser;
import de.hs.inform.lyuz.cookbook.help.ExportInfo;


public class SettingDialog extends javax.swing.JDialog {

    /**
     * Creates new form SettingDialog
     *
     * @param parent
     * @param modal
     */
    public SettingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        init();

        setLocationRelativeTo(null);
    }

    private void init() {
        firstNameTF.setText(ExportInfo.firstName);
        lastNameTF.setText(ExportInfo.lastName);
        titleTF.setText(ExportInfo.title);
        
        hasPicCB.setSelected(ExportInfo.hasPic);
        isColorCB.setSelected(ExportInfo.isColor);
        
        hasCatCB.setSelected(ExportInfo.hasCat);
        hasIndexCB.setSelected(ExportInfo.hasIndex);
        hasSourceCB.setSelected(ExportInfo.hasSource);
        hasRemarkCB.setSelected(ExportInfo.hasRemark);
        hasTimeCB.setSelected(ExportInfo.hasTime);
        hasDifficultyCB.setSelected(ExportInfo.hasDiffculty);
        
        hasCover.setSelected(ExportInfo.hasCover);
        coverTF.setText(ExportInfo.coverPath);
        coverTF.setEnabled(false);
        fileChooseBtn.setEnabled(false);
        
        
        switch (ExportInfo.exportTyp) {
            case "MM":
            case "CML":
            case "MCB":
                hasPicCB.setEnabled(false);
                hasCatCB.setEnabled(false);
                hasIndexCB.setEnabled(false);
                hasCover.setEnabled(false);
                coverTF.setEnabled(false);
                fileChooseBtn.setEnabled(false);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JTextField();
        firstNameTF = new javax.swing.JTextField();
        titleTF = new javax.swing.JTextField();
        hasPicPanel = new javax.swing.JPanel();
        hasPicCB = new javax.swing.JCheckBox();
        isColorCB = new javax.swing.JCheckBox();
        contentPanel = new javax.swing.JPanel();
        hasSourceCB = new javax.swing.JCheckBox();
        hasRemarkCB = new javax.swing.JCheckBox();
        hasCatCB = new javax.swing.JCheckBox();
        hasIndexCB = new javax.swing.JCheckBox();
        hasTimeCB = new javax.swing.JCheckBox();
        hasDifficultyCB = new javax.swing.JCheckBox();
        coverPanel = new javax.swing.JPanel();
        hasCover = new javax.swing.JCheckBox();
        coverTF = new javax.swing.JTextField();
        fileChooseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("title:");

        settingLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingLabel.setText("Settings");

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        lastNameLabel.setText("last name:");

        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        firstNameLabel.setText("first name:");

        lastNameTF.setText("Tester");

        firstNameTF.setText("Rossmann");

        titleTF.setText("CookBook");

        hasPicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("picture"));

        hasPicCB.setSelected(true);
        hasPicCB.setText("picture");
        hasPicCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasPicCBActionPerformed(evt);
            }
        });

        isColorCB.setSelected(true);
        isColorCB.setText("color");

        javax.swing.GroupLayout hasPicPanelLayout = new javax.swing.GroupLayout(hasPicPanel);
        hasPicPanel.setLayout(hasPicPanelLayout);
        hasPicPanelLayout.setHorizontalGroup(
            hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasPicPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(hasPicCB)
                .addGap(18, 18, 18)
                .addComponent(isColorCB)
                .addGap(46, 46, 46))
        );
        hasPicPanelLayout.setVerticalGroup(
            hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasPicPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hasPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasPicCB)
                    .addComponent(isColorCB)))
        );

        contentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("content"));

        hasSourceCB.setText("source");

        hasRemarkCB.setText("remark");

        hasCatCB.setSelected(true);
        hasCatCB.setText("tabel of contents");
        hasCatCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCatCBActionPerformed(evt);
            }
        });

        hasIndexCB.setText("index");

        hasTimeCB.setText("cooktime");
        hasTimeCB.setToolTipText("");

        hasDifficultyCB.setText("difficulty");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(hasRemarkCB)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                .addComponent(hasCatCB)
                                .addGap(39, 39, 39)))
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasIndexCB)
                            .addComponent(hasTimeCB)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(hasSourceCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasDifficultyCB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasIndexCB)
                    .addComponent(hasCatCB))
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasRemarkCB)
                    .addComponent(hasTimeCB))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasSourceCB)
                    .addComponent(hasDifficultyCB))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        coverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("cover"));

        hasCover.setSelected(true);
        hasCover.setText("cover");
        hasCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCoverActionPerformed(evt);
            }
        });

        fileChooseBtn.setText("...");
        fileChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coverPanelLayout = new javax.swing.GroupLayout(coverPanel);
        coverPanel.setLayout(coverPanelLayout);
        coverPanelLayout.setHorizontalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(hasCover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coverTF, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        coverPanelLayout.setVerticalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(hasCover))
            .addComponent(coverTF)
            .addGroup(coverPanelLayout.createSequentialGroup()
                .addComponent(fileChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(settingLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn))
                            .addComponent(coverPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lastNameTF)
                                        .addComponent(firstNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(titleLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(titleTF))
                                            .addComponent(hasPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(firstNameLabel))
                                    .addComponent(lastNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstNameTF, lastNameTF, titleTF});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(settingLabel)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(hasPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lastNameTF, titleTF});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasCatCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCatCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasCatCBActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        ExportInfo.updateBookInfo(firstNameTF.getText(), lastNameTF.getText(),
                titleTF.getText(), hasPicCB.isSelected(), isColorCB.isSelected(), 
                hasCatCB.isSelected(), hasIndexCB.isSelected(), 
                hasSourceCB.isSelected(), hasRemarkCB.isSelected(),
                hasTimeCB.isSelected(), hasDifficultyCB.isSelected(),
                hasCover.isSelected(), coverTF.getText());
        dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void fileChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseBtnActionPerformed
        JFileChooser fc = new JFileChooser() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith("jpg") || f.isDirectory()
                        || f.getName().endsWith("png")
                        || f.getName().endsWith("jpeg")
                        || f.getName().endsWith("gif");
            }
        };
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        int result = fc.showOpenDialog(this);
        switch (result) {
            case JFileChooser.APPROVE_OPTION:
                File file = file = fc.getSelectedFile();
                coverTF.setText(file.getAbsolutePath());
                ExportInfo.coverPath = file.getAbsolutePath();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_fileChooseBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void hasCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCoverActionPerformed
        if (!hasCover.isSelected()) {
            coverTF.setEnabled(false);
            fileChooseBtn.setEnabled(false);
        }else {
            coverTF.setEnabled(true);
            fileChooseBtn.setEnabled(true);
        }
    }//GEN-LAST:event_hasCoverActionPerformed

    private void hasPicCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasPicCBActionPerformed
        if (!hasPicCB.isSelected()) {
            isColorCB.setEnabled(false);
        }else {
            isColorCB.setEnabled(true);
        }
    }//GEN-LAST:event_hasPicCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel coverPanel;
    private javax.swing.JTextField coverTF;
    private javax.swing.JButton fileChooseBtn;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JCheckBox hasCatCB;
    private javax.swing.JCheckBox hasCover;
    private javax.swing.JCheckBox hasDifficultyCB;
    private javax.swing.JCheckBox hasIndexCB;
    private javax.swing.JCheckBox hasPicCB;
    private javax.swing.JPanel hasPicPanel;
    private javax.swing.JCheckBox hasRemarkCB;
    private javax.swing.JCheckBox hasSourceCB;
    private javax.swing.JCheckBox hasTimeCB;
    private javax.swing.JCheckBox isColorCB;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
